pimcore:
    custom_views:
        definitions:
            3:
                treetype: object
                name: Orders
                icon: /bundles/pimcoreadmin/img/flat-white-icons/pimcore-main-icon-cart.svg
                id: 3
                showroot: false
                rootfolder: /Shop/Orders
                classes: {  }
                position: left
                sort: '10'
                expanded: true
                joins: {  }
