pimcore:
    custom_views:
        definitions:
            6:
                treetype: document
                name: Katalog
                icon: /bundles/pimcoreadmin/img/flat-white-icons/pimcore-main-icon-print.svg
                id: 6
                showroot: false
                rootfolder: /print
                position: left
                sort: '5'
                expanded: false
                joins: {  }
                treeContextMenu:
                    document:
                        items:
                            add: true
                            addSnippet: true
                            addLink: true
                            addEmail: true
                            addNewsletter: true
                            addHardlink: true
                            addFolder: true
                            addPrintPage: true
                            paste: true
                            pasteCut: true
                            copy: true
                            cut: true
                            rename: true
                            unpublish: true
                            publish: true
                            delete: true
                            open: true
                            convert: true
                            searchAndMove: true
                            useAsSite: true
                            editSite: true
                            removeSite: true
                            lock: true
                            unlock: true
                            lockAndPropagate: true
                            unlockAndPropagate: true
                            reload: true
