pimcore:
    custom_views:
        definitions:
            7:
                treetype: object
                name: Customers
                icon: /bundles/pimcoreadmin/img/flat-white-icons/businessman.svg
                id: 7
                showroot: false
                rootfolder: '/Customer Management/customers'
                classes:
                    - 0
                position: left
                sort: '6'
                expanded: true
                joins: {  }
