pimcore:
    custom_views:
        definitions:
            8:
                treetype: object
                name: 'Customer Segments'
                icon: /bundles/pimcoreadmin/img/flat-white-icons/pie_chart.svg
                id: 8
                showroot: false
                rootfolder: '/Customer Management/segments'
                classes: '0,1,2'
                position: left
                sort: '6'
                expanded: true
                joins: {  }
                treeContextMenu:
                    object:
                        items:
                            add: true
                            addFolder: true
                            importCsv: true
                            cut: true
                            copy: true
                            paste: true
                            delete: true
                            rename: true
                            reload: true
                            publish: true
                            unpublish: true
                            searchAndMove: true
                            lock: true
                            unlock: true
                            lockAndPropagate: true
                            unlockAndPropagate: true
                            changeChildrenSortBy: true
