<?php

/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Enterprise License (PEL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 *  @license    http://www.pimcore.org/license     GPLv3 and PEL
 */

namespace App\Services\Workflow;

use Pimcore\Model\Element\ElementInterface;
use Pimcore\Workflow\Notes\AbstractCustomHtmlService;
use Pimcore\Workflow\Notes\CustomHtmlServiceInterface;

class CustomHtmlService extends AbstractCustomHtmlService implements CustomHtmlServiceInterface
{
    public function renderHtml(ElementInterface $element): string
    {
        return '<p>Mark <strong><span style="color:#8e44ad">Product</span> </strong>done👍 to publish it on the website.</p>
        <p><q> This message is generated by App\Services\CustomHtmlService</q></p>';
    }
}
