<?php

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace App\Services\Workflow;

use Pimcore\Model\Element\ElementInterface;
use Pimcore\Workflow\Notes\AbstractCustomHtmlService;
use Pimcore\Workflow\Notes\CustomHtmlServiceInterface;

class CustomHtmlService extends AbstractCustomHtmlService implements CustomHtmlServiceInterface
{
    public function renderHtml(ElementInterface $element): string
    {
        return '<p>Mark <strong><span style="color:#8e44ad">Product</span> </strong>done👍 to publish it on the website.</p>
        <p><q> This message is generated by App\Services\CustomHtmlService</q></p>';
    }
}
