<?php 

return [
    1 => [
        "id" => 1,
        "name" => "Show LeftNav",
        "description" => "Defines if left navigation should be visible. \n",
        "key" => "left_nav_show",
        "type" => "bool",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1564138072,
        "modificationDate" => 1566463607
    ],
    2 => [
        "id" => 2,
        "name" => "Root Category",
        "description" => "Defines root category of shop.",
        "key" => "root_category",
        "type" => "object",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565339891,
        "modificationDate" => 1566463620
    ],
    3 => [
        "id" => 3,
        "name" => "Navigation Extension Point",
        "description" => "Defines and extension point for adding dynamic elements to navigation.",
        "key" => "navigation_extension_point",
        "type" => "select",
        "data" => "",
        "config" => "category",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565339906,
        "modificationDate" => 1566463638
    ],
    4 => [
        "id" => 4,
        "name" => "LeftNav Start Node",
        "description" => "Start node for left navigation.",
        "key" => "left_nav_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565342864,
        "modificationDate" => 1566463647
    ],
    5 => [
        "id" => 5,
        "name" => "Header Color",
        "description" => "Specify header color. ",
        "key" => "header_color",
        "type" => "select",
        "data" => NULL,
        "config" => "black,red,purple,blue",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565351556,
        "modificationDate" => 1566463656
    ],
    6 => [
        "id" => 6,
        "name" => "Sidebar Snippet",
        "description" => "Specify a sidebar snippet.",
        "key" => "sidebar",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565795435,
        "modificationDate" => 1566463760
    ],
    7 => [
        "id" => 7,
        "name" => "News Default Document",
        "description" => "Defines the default news document (for canonical url)",
        "key" => "news_default_document",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565959224,
        "modificationDate" => 1566463680
    ],
    8 => [
        "id" => 8,
        "name" => "Print Register Type",
        "description" => "Defines color and size of register.",
        "key" => "print_register_type",
        "type" => "select",
        "data" => NULL,
        "config" => "orange,red,violett,green,blue,yellow",
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1566309612,
        "modificationDate" => 1566463694
    ],
    9 => [
        "id" => 9,
        "name" => "Print Register Title",
        "description" => "Defines title for register.",
        "key" => "print_register_title",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1566309660,
        "modificationDate" => 1566463704
    ],
    10 => [
        "id" => 10,
        "name" => "Terms & Conditions Page",
        "description" => "Link to Terms and Conditions page\n",
        "key" => "terms_and_conditions",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1566463224,
        "modificationDate" => 1566463592
    ]
];
