<?php 

return [
    1 => [
        "id" => 1,
        "name" => "Show LeftNav",
        "description" => NULL,
        "key" => "left_nav_show",
        "type" => "bool",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1564138072,
        "modificationDate" => 1566411234
    ],
    2 => [
        "id" => 2,
        "name" => "Root Category",
        "description" => "",
        "key" => "root_category",
        "type" => "object",
        "data" => "",
        "config" => "",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565339891,
        "modificationDate" => 1566411239
    ],
    3 => [
        "id" => 3,
        "name" => "Navigation Extension Point",
        "description" => "",
        "key" => "navigation_extension_point",
        "type" => "select",
        "data" => "",
        "config" => "category",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565339906,
        "modificationDate" => 1565339982
    ],
    4 => [
        "id" => 4,
        "name" => "LeftNav Start Node",
        "description" => "",
        "key" => "left_nav_start_node",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565342864,
        "modificationDate" => 1566411247
    ],
    5 => [
        "id" => 5,
        "name" => "Header Color",
        "description" => "",
        "key" => "header_color",
        "type" => "select",
        "data" => NULL,
        "config" => "black,red,purple,blue",
        "ctype" => "document",
        "inheritable" => FALSE,
        "creationDate" => 1565351556,
        "modificationDate" => 1566410892
    ],
    6 => [
        "id" => 6,
        "name" => "Sidebar Snippet",
        "description" => NULL,
        "key" => "sidebar",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565795435,
        "modificationDate" => 1565795447
    ],
    7 => [
        "id" => 7,
        "name" => "News Default Document",
        "description" => NULL,
        "key" => "news_default_document",
        "type" => "document",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1565959224,
        "modificationDate" => 1565959238
    ],
    8 => [
        "id" => 8,
        "name" => "Print Register Type",
        "description" => "",
        "key" => "print_register_type",
        "type" => "select",
        "data" => NULL,
        "config" => "orange,red,violett,green,blue,yellow",
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1566309612,
        "modificationDate" => 1566309657
    ],
    9 => [
        "id" => 9,
        "name" => "Print Register Title",
        "description" => "",
        "key" => "print_register_title",
        "type" => "text",
        "data" => NULL,
        "config" => NULL,
        "ctype" => "document",
        "inheritable" => TRUE,
        "creationDate" => 1566309660,
        "modificationDate" => 1566309674
    ]
];
