
SET NAMES utf8mb4;

INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1161,'paymentProvider','paypal','9CT34444M22539158','ZPHG5HTTA7KM2','sb-n9hfj12488071@personal.example.com','John','Doe');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1164,'paymentProvider','paypal','6P219778U2879173E','8K7SZCFPV9FNN','dino.flintstone@stone.age','Dino','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1167,'paymentProvider','paypal','6JJ73082Y6212093P','ZPHG5HTTA7KM2','sb-n9hfj12488071@personal.example.com','John','Doe');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1169,'paymentProvider','paypal','2EM467546N444340L','ZPHG5HTTA7KM2','sb-n9hfj12488071@personal.example.com','John','Doe');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1171,'paymentProvider','paypal','25G06452DD907934U','E5MVCRWZCLVGC','pebbles.flintstone@stone.age','Pebbles','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1174,'paymentProvider','paypal','0PW47704US056523W','KM74HEUDXRKW8','wilma.flintstone@stone.age','Wilma','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1177,'paymentProvider','paypal','2WD483862M3756428','9JD48T3MNQAHE','fred.flintstone@stone.age','Fred','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1179,'paymentProvider','paypal','47K11814GM581932X','CQKZHP8X94AXG','fred.flintstone@stone.age','Fred','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1182,'paymentProvider','paypal','6R3238856S495354E','XQADWG5K37MDG','fred.flintstone@stone.age','Fred','Flintstone');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1184,'paymentProvider','paypal','8KG85242WB406050N','ZPHG5HTTA7KM2','sb-n9hfj12488071@personal.example.com','John','Doe');
INSERT INTO object_brick_store_PaymentProviderPayPalSmartButton_EF_OSO (`id`,`fieldname`,`configurationKey`,`auth_orderID`,`auth_payerID`,`auth_email_address`,`auth_given_name`,`auth_surname`) VALUES (1186,'paymentProvider','paypal','6B458608LD1779402','ZPHG5HTTA7KM2','sb-n9hfj12488071@personal.example.com','John','Doe');
