
SET NAMES utf8mb4;

INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1120,'en','Classic Expo Salzburg','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of automotive design. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1121,'en','Auto Fair Salzburg \'19','\"International vintage car&nbsp;fair.\" A vintage car is, in the most general sense, an old automobile, and in the narrower senses of car enthusiasts and collectors, it is a car from the period of 1919 to 1930. Such enthusiasts have categorization schemes for ages of cars that enforce distinctions between antique cars, vintage cars, classic cars, and so on. The classification criteria vary, but consensus within any country is often maintained by major car clubs, for example the Vintage Sports-Car Club (VSCC) in the UK. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1122,'en','Austria Retro Classics','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of automotive design. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1123,'en','Vienna Auto Show','\"International Automobiles, Spare Parts and Accessories Industry trade fair.\" Vienna Auto Show, This event showcases product like Design, performance, efficiency in a production of the special class. Attendees will be delighted with new car models of many automobile brands, the Concept &amp; Show Cars, the Austria and European premieres. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1124,'en','Custom Wheels Vienna','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of automotive design. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1125,'en','International Motor Show','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of automotive design. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1126,'en','Thermen Classic 2019','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of automotive design. ');
INSERT INTO object_localized_query_EV_en (`ooo_id`,`language`,`title`,`description`) VALUES (1127,'en','Oldtimer Expo 2019','\"The vintage era in the automotive world was a time of transition.\" The car started off in 1919 as still something of a rarity, and ended up, in 1930, well on the way towards ubiquity. In fact, automobile production at the end of this period was not matched again until the 1950s. In the intervening years, most industrialized countries built nationwide road systems with the result that, towards the end of the period, the ability to negotiate unpaved roads was no longer a prime consideration of autom ');
