
SET NAMES utf8mb4;

INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (563,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (696,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (697,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (698,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (699,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (760,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (761,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (762,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO object_store_EF_FD (`oo_id`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`) VALUES (872,22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL);
