
SET NAMES utf8mb4;

INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('61',NULL,'@AppBundle\\Controller\\CheckoutController','confirmationMail',NULL,'','','','','','Order Confirmation for {{ ordernumber }}',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('93',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','Password Recovery',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('105',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','Newsletter Confirmation',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('111',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','We have more for you',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('144',NULL,'@AppBundle\\Controller\\CheckoutController','confirmationMail',NULL,'','','','','','Order Confirmation for {{ ordernumber }}',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('145',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','Password Recovery',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('146',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','Newsletter Confirmation',NULL);
INSERT INTO documents_email (`id`,`module`,`controller`,`action`,`template`,`to`,`from`,`replyTo`,`cc`,`bcc`,`subject`,`missingRequiredEditable`) VALUES ('147',NULL,'@AppBundle\\Controller\\DefaultController','genericMail',NULL,'','','','','','We have more for you',NULL);
