
SET NAMES utf8mb4;

INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1040','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','3297.8','EUR','{\"cvc\":\"***\",\"expiryDate\":\"12/2021\",\"holder\":\"\",\"id\":\"s-crd-rpb3nfywev0y\",\"number\":\"471110******0000\"}','s-pay-258050','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1043','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','42681.97','EUR','{\"cvc\":\"***\",\"expiryDate\":\"12/2021\",\"holder\":\"\",\"id\":\"s-crd-h6lwoa24zea2\",\"number\":\"545301******9543\"}','s-pay-258057','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1051','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','84481.11','EUR','{\"cvc\":\"***\",\"expiryDate\":\"03/2020\",\"holder\":\"\",\"id\":\"s-crd-lk061jguw0jg\",\"number\":\"471110******0000\"}','s-pay-258312','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1055','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Sofort','61963.83','EUR','{\"id\":\"s-sft-ikpeyojcqdfa\"}','s-pay-258315','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1065','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','801.85','EUR','{\"id\":\"s-ppl-nqlk41s0uhbg\"}','s-pay-258317','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1067','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','7097.8','EUR','{\"cvc\":\"***\",\"expiryDate\":\"03/2030\",\"holder\":\"\",\"id\":\"s-crd-duogqc6m4kns\",\"number\":\"545301******9543\"}','s-pay-258318','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1070','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','5195.95','EUR','{\"cvc\":\"***\",\"expiryDate\":\"03/2030\",\"holder\":\"\",\"id\":\"s-crd-dk2ppqeipqv2\",\"number\":\"471110******0000\"}','s-pay-258332','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1084','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','13495.95','EUR','{\"id\":\"s-ppl-098xvvpsqxpe\"}','s-pay-259933','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1089','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','88662.14','EUR','{\"cvc\":\"***\",\"expiryDate\":\"03/2033\",\"holder\":\"\",\"id\":\"s-crd-uxtweibtv9zw\",\"number\":\"471110******0000\"}','s-pay-259950','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1103','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','5595.95','EUR','{\"email\":\"p*************r@h**********e\",\"id\":\"s-ppl-5lxdjx7sxobc\"}','s-pay-260327','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1107','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','8995.95','EUR','{\"email\":\"p*************r@h**********e\",\"id\":\"s-ppl-7rosnqhn9amu\"}','s-pay-260875','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1109','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','22173.99','EUR','{\"email\":\"p*************r@h**********e\",\"id\":\"s-ppl-kot6mjewxigq\"}','s-pay-260906','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1112','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Card','1366.55','EUR','{\"cvc\":\"***\",\"expiryDate\":\"02/2021\",\"holder\":\"\",\"id\":\"s-crd-1uywhyadzz8w\",\"number\":\"545301******9543\"}','s-pay-260976','','','s-chg-1');
INSERT INTO object_brick_store_PaymentProviderHeidelPay_EF_OSO (`o_id`,`fieldname`,`auth_paymentMethod`,`auth_amount`,`auth_currency`,`auth_paymentType`,`auth_paymentReference`,`auth_clientMessage`,`auth_merchantMessage`,`auth_chargeId`) VALUES ('1117','paymentProvider','heidelpayPHP\\Resources\\PaymentTypes\\Paypal','31915.07','EUR','{\"email\":\"p*************r@h**********e\",\"id\":\"s-ppl-ys3pt5mp30ga\"}','s-pay-261019','','','s-chg-1');
