
SET NAMES utf8mb4;

INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('33',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('35',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('36',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'includes/sidebar.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('106',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('107',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('114',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'includes/sidebar.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('116',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('117',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig',NULL,NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('150',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'includes/sidebar.html.twig','0',NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('166',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig','33',NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('167',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig','35',NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('168',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig','106',NULL);
INSERT INTO documents_snippet (`id`,`module`,`controller`,`action`,`template`,`contentMasterDocumentId`,`missingRequiredEditable`) VALUES ('169',NULL,'AppBundle\\Controller\\DefaultController::defaultAction',NULL,'snippets/standard-teaser.html.twig','107',NULL);
