
SET NAMES utf8mb4;

INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (563,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (696,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (697,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (698,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (699,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (760,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (761,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (762,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO object_query_EF_FD (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`defaultOrderByInheritance`,`orderByAsc`,`orderByDesc`,`ajaxReload`,`infiniteScroll`,`limitOnFirstLoad`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`) VALUES (872,'EF_FD','FilterDefinition',22,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL);
