
SET NAMES utf8mb4;

INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1015,1,'male','Fred','Flintstone','fred.flintstone@stone.age','Floridusgasse 18','1020','Vienna','AT',NULL,'298923c8190045e91288b430794814c4','$2y$10$G9FRglojyv8n3Mme4xBjvuXQbRWkmL5DctLzAkWNWcp94ug86oddi',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1016,1,'female','Wilma','Flintstone','wilma.flintstone@stone.age','Floridusgasse 18','1020','Vienna','AT',NULL,'08fe2621d8e716b02ec0da35256a998d','$2y$10$2nQSeO/Py3EnYXhaYmPhEOEyveK13qJx2N9lJP4WnWBJZ3RDmLBTq',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1017,1,'female','Pebbles','Flintstone','pebbles.flintstone@stone.age','Floridusgasse 18','1020','Vienna','AT',NULL,'5d616dd38211ebb5d6ec52986674b6e4','$2y$10$u08fYxOqN5A2gTuyVWUc/.BqLXWYYi7alTHHlDR0RBdvfdFGWm0Ty',NULL,NULL,NULL,NULL,0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1018,1,'male','Dino','Flintstone','dino@stone.age','Floridusgasse 18','1020','Vienna','AT',NULL,'ef50c335cca9f340bde656363ebd02fd','$2y$10$HdhF7vIXAfUNcXyVo1D45.spY.mWJ7AEhwEvmUM96ves2MD6SXjXG',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1019,1,'male','Barney','Rubble','barney.rubble@modern.age','Rudolstädter Straße 21','63741','Aschaffenburg','DE',NULL,'03e0704b5690a2dee1861dc3ad3316c9','$2y$10$Xf2Nmz1DeXgXnnKcXULIr.2lHAJezSITgn6RBNiiUgp7sOAeLT8T.',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1020,1,'female','Betty','Rubble','betty.rubble@modern.age','Rudolstädter Straße 21','63741','Aschaffenburg','DE',NULL,'65cc2c8205a05d7379fa3a6386f710e1','$2y$10$G5N07ujZjeLg.ari1MAJr.mDRUUAtUMdIZzJbG2uKOsY4cccE6j5m',NULL,NULL,NULL,'en',1,116,1,1,1,117,'HereCouldHaveBeenYourToken');
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1021,1,'male','Bamm-Bamm','Rubble','bamm@modern.age','Rudolstädter Straße 21','63741','Aschaffenburg','DE',NULL,'0768281a05da9f27df178b5c39a51263','$2y$10$ewMRxNi93BscjvLF9l6JTeTfISCFgQ18na3VsNtYAsUCZ3UGdDWDi',NULL,NULL,NULL,'en',0,NULL,0,NULL,1,136,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1022,1,'male','Joe','Rockhead','joe.rockhead@middle.age','1502  Pratt Avenue','98109','Seattle','US',NULL,'93d65641ff3f1586614cf2c1ad240b6c','$2y$10$7AOxkqfLb5c8iD0rhnPmZO5LeW56A0l1eQqOTlePQVxSnQqRVhf.m',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1023,1,'female','Pearl','Slaghoople','pearl.slaghoople@middle.age','4780  Haul Road','94015','Daly City','US',NULL,'ce5140df15d046a66883807d18d0264b','$2y$10$spx7NcWf9q/oKGhkq7MsKerK.tpUONgI1cTjdFcThqcxjUcdyKPSC',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1024,1,'male','Tex','Hardrock','tex.hardrock@middle.age','Holzstrasse 75','5020','Salzburg','AT',NULL,'021bbc7ee20b71134d53e20206bd6feb','$2y$10$wBXWsfrjT0.7wVQCc5xqGOgTj48BaNf6gjvLCmizUtu.ko07v/ZGe',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1025,1,'male','Sam','Slagheap','sam@buffalo.lodge','Genslerstraße 42','13158','Berlin Rosenthal','DE',NULL,'82b8a3434904411a9fdc43ca87cee70c','$2y$10$0F.EhcZaTPI62mI717txSeRDLH9S66guhJV.qk.4tYUCP0Y7/3Qmy',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1045,1,'male','Dino','Flinttone','dino@stone.aeg','Floridusgasse 18','1020','Vienna','AU',NULL,'a0e2a2c563d57df27213ede1ac4ac780','$2y$10$R4AcuMLG3jb6U1vYnJTZ4OmKx792jWar.o3xVAJWH/GfkjSn5YvvK',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
INSERT INTO object_store_CU (`oo_id`,`active`,`gender`,`firstname`,`lastname`,`email`,`street`,`zip`,`city`,`countryCode`,`phone`,`idEncoded`,`password`,`company`,`passwordRecoveryToken`,`passwordRecoveryTokenDate`,`customerLanguage`,`newsletter__consent`,`newsletter__note`,`newsletterActive`,`newsletterConfirmed`,`profiling__consent`,`profiling__note`,`newsletterConfirmToken`) VALUES (1048,1,'male','Barney','Rubbl','some-other-mail@ice.age','Rudolstaedter Strasse 21','63741','Aschaffenburg','DE',NULL,'7cce53cf90577442771720a370c3c723','$2y$10$7JJOiYW.UZOAhxVEyMDXlOwXGlLnWa8kAl7rAM2hv8CIq9fBfgQ8.',NULL,NULL,NULL,'en',0,NULL,0,NULL,0,NULL,NULL);
