
SET NAMES utf8mb4;

INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1120,'de',' Klassische Expo Salzburg','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1121,'de','Auto Messe Salzburg \'19','\"Internationale Oldtimermesse.\" Ein Oldtimer ist im weitesten Sinne ein altes Automobil, und im engeren Sinne von Autoenthusiasten und Sammlern ist es ein Auto aus der Zeit von 1919 bis 1930. Solche Enthusiasten haben Kategorisierungsschemata für das Alter von Autos, die Unterscheidungen erzwingen zwischen antiken Autos, Oldtimern, Oldtimern und so weiter. Die Einstufungskriterien variieren, aber innerhalb eines Landes wird der Konsens häufig von großen Autoclubs gewahrt, beispielsweise dem Vintage Sports-Car Club (VSCC) in Großbritannien. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1122,'de','Österreich Retro Classics','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1123,'de','Wien Auto Show','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1124,'de','Kundenspezifische Räder Wien','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1125,'de','Internationale Automobil Ausstellung','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1126,'de','Thermen Classic 2019','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
INSERT INTO object_localized_query_EV_de (`ooo_id`,`language`,`title`,`description`) VALUES (1127,'de','Oldtimer Expo 2019','\"Die Vintage-Ära in der Automobilwelt war eine Zeit des Übergangsn.\" Das Auto startete 1919 noch als Rarität und endete 1930 auf dem Weg zur Allgegenwart. Tatsächlich war die Automobilproduktion am Ende dieses Zeitraums erst in den 1950er Jahren wieder vergleichbar. In den vergangenen Jahren bauten die meisten Industrieländer landesweite Straßensysteme auf, so dass die Fähigkeit, unbefestigte Straßen zu befahren, gegen Ende des Zeitraums nicht mehr im Vordergrund des Autodesigns stand. ');
