pimcore:
    perspectives:
        definitions:
            Commerce:
                elementTree:
                    -
                        type: customview
                        id: 3
                        position: left
                        expanded: true
                        hidden: false
                        sort: 0
                    -
                        type: objects
                        position: left
                        expanded: false
                        hidden: false
                        sort: 1
                    -
                        type: customview
                        id: 7
                        position: right
                        expanded: true
                        hidden: false
                        sort: 0
                    -
                        type: customview
                        id: 8
                        position: right
                        expanded: false
                        hidden: false
                        sort: 1
                    -
                        type: assets
                        position: right
                        expanded: false
                        hidden: false
                        sort: 2
                    -
                        type: documents
                        position: right
                        expanded: false
                        hidden: false
                        sort: 3
                iconCls: null
                icon: /bundles/pimcoreadmin/img/flat-white-icons/shopping-cart.svg
                toolbar:
                    file: true
                    extras: false
                    marketing: false
                    settings: false
                    search: true
                    ecommerce: true
