pimcore:
    perspectives:
        definitions:
            DAM:
                elementTree:
                    -
                        type: documents
                        position: left
                        expanded: false
                        hidden: true
                        sort: 0
                    -
                        type: assets
                        position: left
                        expanded: false
                        hidden: false
                        sort: 1
                    -
                        type: objects
                        position: left
                        expanded: false
                        hidden: true
                        sort: 2
                    -
                        type: customview
                        name: Products
                        hidden: 'true'
                        sort: 3
                        position: left
                    -
                        type: customview
                        name: Orders
                        hidden: 'true'
                        sort: 4
                        position: left
                iconCls: pimcore_nav_icon_asset
                icon: null
                toolbar:
                    file: 1
                    extras:
                        hidden: true
                    marketing:
                        hidden: true
                    settings:
                        items:
                            documentTypes: false
                            predefinedProperties: false
                            system: false
                            routes: false
                            adminTranslations: false
                            website: false
                            users: false
                            objects: false
                            cache: false
                    search:
                        items:
                            objects: false
                            documents: false
                            esBackendSearch: false
                    ecommerce: false
